### ISSUE TITLE
support Scala 2.12

### ISSUE THREAD

**Issue by xuwei-k** [fluent/fluent-logger-scala#29]
https://github.com/xerial/fluentd-standalone/pull/3
fluent-logger-scala use fluentd-standalone in test.
fluentd-standalone 0.1.2 depends on Scala 2.10 https://oss.sonatype.org/content/repositories/releases/org/xerial/fluentd-standalone/0.1.2/fluentd-standalone-0.1.2.pom
need cross build (or temporary disable tests when Scala 2.12)

/cc @xerial

**Comment by oza** [comment]
@xuwei-k Thanks for your report. 

@xerial could you check whether fluentd-standalone for Scala 2.12 can be published?

**Comment by xerial** [comment]
ok

**Comment by xerial** [comment]
Just released fluentd-standalone 0.14.11 (Supporting Scala 2.11, 2.12, but dropped Scala 2.10 support)

**Comment by xerial** [comment]
I'll work on supporting Scala 2.12

**Comment by xerial** [comment]
Just released 0.7.0 with Scala 2.12 support
