### ISSUE TITLE
What happened to the master branch?

### ISSUE THREAD

**Issue by fujimotos** [fluent/fluent-logger-scala#32]
It seems that the current 'fluent-logger-scala' project uses the *develop* branch
as its default branch, and the *master* branch has not been updated since v0.6.0.

Specifically, the last update of the master branch was more than a year ago:

> https://github.com/fluent/fluent-logger-scala/commits/master

Does this mean that the master branch is now deprecated?
Or is it just left behind by some mistake?

#### Why is this a problem?

Some external documentations assume that the master branch is the latest tip of
the project. For this reason, they are still relying on the outdated information.

For example, the official documentation still refers to the outdated CHANGELOG file,
which is still referring to v0.6.0 as the latest stable:

https://github.com/fluent/fluentd-docs/blob/master/docs/v1.0/scala.txt#L46

**Comment by xerial** [comment]
Yes. The current master branch has been deprecated after dropping a support for Scala 2.10, but we left it for avoiding the complexity of merging the latest branch (develop) with the deprecated master code.

And the reference in the fluentd documentation should be fixed. I think we should send a PR to fluentd.

**Comment by fujimotos** [comment]
Thanks for the swift response!

> And the reference in the fluentd documentation should be fixed.

I submit a pull request to `fluentd-docs` that addresses the above issue.
So it should be fixed soon...
